---
site: bookdown::bookdown_site
title: 'A tool for simulating multi-response linear model data'
date: "`r format(Sys.time(), '%Y-%m-%d')`"
# Author Information
author:
  - name: Raju Rimal
    email: raju.rimal@nmbu.no
    affiliation: KBM
    footnote: Corresponding Author
  - name: Trygve Almøy
    email: trygve.almoy@nmbu.no
    affiliation: KBM
  - name: Solve Sæbø
    email: solve.sabo@nmbu.no
    affiliation: NMBU
address:
  - code: KBM
    address: Faculty of Chemistry and Bioinformatics, Norwegian University of Life Sciences, Ås, Norway
  - code: NMBU
    address: Prorector, Norwegian University of Life Sciences, Ås, Norway
# Template Options
classoption: ['review']
monofont: 'sourcecodepro'
monofontoptions: "Scale=0.7"
colorlinks: true
# linespacing: 1.5
# Bibliography Setup
bibliography: ['ref-db.bib', 'packages.bib']
biblio-title: References
biblio-style: elsarticle-harv
# Extra Information
github-repo: therimalaya/simrel-m
url: 'http\://therimalaya.github.io/simrel-m'
knit: 'bookdown::render_book'
# Abstract and Keywords
keywords: ['`simrel` package in r', 'data simulation', 'linear model']
abstract: |
  Data science is generating enormous amounts of data, and new and advanced analytical methods are constantly being developed to cope with the challenge of extracting information from such "big-data". Researchers often use simulated data to assess and document the properties of these new methods, and in this paper we present an extension to the R-package `simrel`, which is a versatile and transparent tool for simulating linear model data with an extensive range of adjustable properties.
  The method is based on the concept of relevant components, and is equivalent to the newly developed envelope model. It is a multi-response extension of R-package `simrel` which is available in R-package repository CRAN, and as `simrel` the new approach is essentially based on random rotations of latent relevant components to obtain a predictor matrix $\mathbf{X}$, but in addition we introduce random rotations of latent components spanning a response space in order to obtain a multivariate response matrix $\mathbf{Y}$.
  The properties of the linear relation between $\mathbf{X}$ and $\mathbf{Y}$ are defined by a small set of input parameters which allow versatile and adjustable simulations. Sub-space rotations also allow for generating data suitable for testing variable selection methods in multi-response settings.
  The method is implemented as an update to the R-package `simrel`.
---

# Introduction #

Technological advancement has opened a door for complex and sophisticated scientific experiments that were not possible before. Due to this change, enormous amounts of raw data are generated which contain massive information but is difficult to excavate. Finding information and performing scientific research on these raw data has now become another problem. In order to tackle this situation new methods are being developed. However, before implementing any method, it is essential to test its performance and explore its properties. Often, researchers use simulated data for the purpose which itself is a time-consuming process. The main focus of this paper is to present a simulation method, along with an extension to the r-package called `simrel`, that is versatile in nature and yet simple to use. 

The simulation method we are presenting here is based on the principle of relevant space for prediction [@helland1994comparison] which assumes that there exists a y-relevant subspace in the complete space of predictor variables that is spanned by a subset of eigenvectors of these predictor variables. Our extension to this principle is to introduce a subspace in $\mathbf{y}$ (material space) which contains the information that predictor space is relevant for. The concept of response reduction to the material space in response variable was introduced by @cook2010envelope. Our r-package based on this principle lets the user specify various population properties such as;  which latent components in $\mathbf{x}$ are relevant for a latent subspace of the responses $\mathbf{y}$ and the collinearity structure of $\mathbf{x}$. This enables the possibility to construct data for evaluating estimation methods and methods developed for variable selection. 

Among several publications on simulation, @johnson2013multivariate; @ripley2009stochastic and @gamerman2006markov have exhaustively discussed the topic. In particular, methods based on covariance structure has been discussed by @arteaga2010simulate; @arteaga2013building and @camacho2017generation, following approaches to find simulated data satisfying the desired correlation structure. In addition, many publications have implemented simulated data in order to investigate new estimation methods and prediction strategies [see: @cook2015simultaneous; @cook2013envelopes; @helland2012near]. However, most of the simulations in these studies were developed to address their specific problem. A systematic tool for simulating linear model data with single response, which could serve as a general tool for all such comparisons, was presented in @saebo2015simrel and as the r-package `simrel`. This paper extends `simrel` in order to simulate linear model data with multivariate response. The github repository of the package at [http://github.com/simulatr/simrel](http://github.com/simulatr/simrel) has rich documentation with many examples and cases along with detailed descriptions of simulation parameters. In the following two sections, the discussion encircle the mathematical framework behind. In addition, in [section \@ref(implementation)](#implementation) and [\@ref(web-interface)](#web-interface) we have also discussed the input parameters needed for simrel function in brief. In [section \@ref(implementation)](#implementation), an implementation is presented as a case example and the [final section](#web-interface) introduces the shiny web application for this tool.

```{r load-packages, echo=FALSE, message=FALSE, warning=FALSE}
knitr::opts_knit$set(
  root.dir = "/Users/therimalaya/Dropbox/Papers/01-simrel-m/"
)
pkgs <- c("simrel", "ggplot2", "reshape2")
for (pkg in pkgs) require(pkg, character.only = T)
source(file.path(getwd(), "scripts/00-function.R"))
source(file.path(getwd(), "scripts/00-plot-function.R"))
```


