#+TITLE: Review on Simrel Paper
#+AUTHOR: Raju Rimal
#+STARTUP: latexpreview
#+STARTUP: overview
#+STARTUP: indented
#+STARTUP: aligned
#+STARTUP: inlineimages
#+HTML_MATHJAX: align: left indent: 5em tagside: left font: Neo-Euler extensions: Cancel
#+LATEX_HEADER: \usepackage[utf8]{inputenc}
#+LATEX_HEADER: \usepackage[T1]{fontenc}
#+LATEX_HEADER: \usepackage{cancel}
#+PANDOC_OPTIONS: latex-engine:xelatex 
#+PANDOC_OPTIONS: include-after-body:footer.html
#+PANDOC_VARIABLES: fontsize:12pt papersize:A4 geometry:margin=1in fontfamily:palatino
#+HTML_HEAD: <link rel="stylesheet" href="latex.css"/>
#+HTML_HEAD: <link rel="stylesheet" href="tufte.css"/>
#+HTML_HEAD: <link rel="stylesheet" href="custom.css"/>
#+BIBLIOGRAPHY: ../ref-db.bib
#+LATEX_HEADER: \usepackage[style=authoryear,dashed=false]{biblatex}

* TODO Corrections in Paper
DEADLINE: <2017-10-29 sø.>
** Introduction 
*** Page 2:
- Add references [@johnson2013multivariate] along with [@ripley2009stochastic] and [@gamerman2006markov].
- *Line 2 last paragraph:* In particular, methods based on covariance structure has been discussed by [@arteaga2010simulate, @arteaga2013building, @camacho2017generation], which follows an algorithmic approach to find simulated data satisfying the desired correlation structure. 
*** Page3:
*After first Paragraph:*
- The github repository of the package at http://github.com/simulatr/simrel has rich documentation with many examples and cases along with detail description on simulation parameters. 
- In the following two section, discussion encircle the mathematical framework behind. 
- In addition, section-4 and 5 have also discussed about the input parameters needed for simrel function in brief. 
- In section 4, an implementation is presented as an example of use-cases and the final section introduce shiny web application for this tool.
** Relevant Components
*** Page 6
- Equation number to the expression of generating lambda from gamma. Subscript changed from $j$ to $i$. 
- *Added to equation of $\gamma$:* Hence, we can write $\Sigma_{zz} = \Lambda = \text{diag}(\lambda_1, \ldots, \lambda_p)$.
- +Here we assume that $\mathbf{w}$'s are independent and has mutinormal distribution wnith variances 1, hence $\boldsymbol{\Sigma}_{ww} = \mathbf{I}_m$.+ In similar manner, a parametric representation of eigenvalues corresponding to $\Sigma_{ww}$ is adopted as, \[\kappa_j = e^{-\eta(j - 1), \eta > 0 \text{ and } j = 1 \ldots m}\] Here, the decline of eigenvalues becomes steep as $\eta$ gets far from zero. At $\eta = 0$, all $\boldsymbol{w}$ will have equal variance. Hence we can write $\Sigma_{ww} = \text{diag}(\kappa_1, \ldots, \kappa_m)$.
*** Page 8 
- $\cancel{\Sigma_{ww} = \mathbf{I}_{m}}$ \[\Sigma_{ww} = \text{diag}(\kappa_1, \ldots, \kappa_m)\]
- $\cancel{\rho_w^2 = \Sigma_{zw}^t\Lambda^{-1}\Sigma_{zw}\Sigma_{ww}^{-1}}$ 
  \[\rho_{w}^2 = \Sigma_{zw}^t\Lambda^{-1}\Sigma_{zw}\Sigma_{ww}^{-1} = 
  \begin{bmatrix}
    \sum_{i = 1}^p\frac{\sigma_{i1}^2}{\lambda_i\kappa_1} & \ldots & \sum_{i=1}^p\frac{\sigma_{i1}\sigma_{im}}{\lambda_i\kappa_1} \\
    \vdots & \ddots & \vdots \\
    \sum_{i=1}^p\frac{\sigma_{i1}\sigma_{im}}{\lambda_i\kappa_m} & \ldots & \sum_{i = 1}^p\frac{\sigma_{im}^2}{\lambda_i\kappa_m}
  \end{bmatrix} \]
- $\cancel{\rho_{w_j}^2 = \sum_{i = 1}^p\frac{\sigma_{ij}^2}{\lambda_i}}$ is replaced by, 
\[\rho_{w_j}^2 = \sum_{i = 1}^p\frac{\sigma_{ij}^2}{\lambda_i\kappa_j}\]
- $\cancel{\rho_{w_j}^2 = \sum_{i \in \mathcal{P}_j}\frac{\sigma_{ij}^2}{\lambda_i}}$ 
\[\rho_{w_j}^2 = \sum_{i \in \mathcal{P}_j} \frac{\sigma_{ij}^2}{\lambda_i\kappa_j}\]
- $\cancel{\sigma_{ij} = \text{Sign}(\mathcal{S}_i)\sqrt{\frac{\rho_{wj}^2\left|\mathcal{S}_i\right|}{\sum_{k\in\mathcal{P}_j}\left|\mathcal{S}_k\right|}\lambda_i}}$
  \[\sigma_{ij} = \text{Sign}(\mathcal{S}_i)\sqrt{\frac{\rho_{wj}^2\left|\mathcal{S}_i\right|}{\sum_{k\in\mathcal{P}_j}\left|\mathcal{S}_k\right|}\lambda_i\kappa_j}\]
  for $i \in \mathcal{P}_j$ and $j = 1, \ldots m$
** Implementation
*** Page 13
- ~gamma~ $\rightarrow \gamma$ (referred to corresponding equation)
- *Line 8:* Here, in this example we have assumed that all $w$ 's have equal variance, i.e. $\Sigma_{ww} = I_m$
- *Line 11:* Although the simulation method is well equipped to simulate data with $p \gg n$, for incorporating envelope estimation methods which are based on maximization of likelihood, we have chosen $n > p$ situation in the example.
- *Figure 3 Caption added:* Here (a) is the covariance structure of latent space which is rotated by the block diagonal rotation matrix in (b) resulting the covariance structure of simulated data in (c).
** Web Interface
*** Page 16
- +(uses ~simrel~ package in CRAN)+, +(not yet available in CRAN)+, +(~simrel-m~)+.
- *second last line* Users can also download simulated data in JSON and CSV format.
*** Page 17
- *After first paragraph:* An R expression equivalent to the input parameters as shown in Figure - 5(b) can be written as,
#+BEGIN_SRC r
  simrel(
    n      = 200, 
    # Number of training observations
    ntest  = 50, 
    # Number of test observations
    p      = 15, 
    # Number of predictor variables
    q      = c(5, 4), 
    # Number of relevant predictors
    relpos = list(c(1, 2), c(3, 4, 6)), 
    # Position of predictor components
    R2     = c(0.8, 0.7), 
    # Coefficient of determination for each response components
    m      = 4, 
    # Number of response variables
    gamma  = 0.6, 
    # Decay factor of eigenvalues of predictors
    eta    = 0, 
    # Decay factor of eigenvalues of responses
    ypos   = list(c(1, 3), c(2, 4)), 
    # Combination of response components on rotation
    type   = "multivariate"
  )
#+END_SRC
- Figure-5 moved to this page
- *Figure-5 Caption:* Web interface of shiny application of `simrel`: (*a*) Buttons to trigger simulation, (*b*) Parameters for simulation -- here with these settings 200 training sets (~n~) and 50 test sets (~ntest~) will be simulated with 15 predictor variables (~p~) and 4 response variables (~m~). The 4 response variables will have 2 true latent dimension which is referred as /response components/. The first response component is rotated together with third (uninformative) response component and second response component is rotated together with fourth (uninformative) response components (~ypos~). Out of 15 predictors, 5 will be relevant for first response component and 4 will be relevant for second response component (~q~). The relevant principal components of the predictor variables are /predictor components/. The 5 predictor variables which are relevant for first response components span the same space as the predictor components at position 1 and 2. Similarly, the 4 predictor variables which are relevant for second response components span the same space as the predictor components at position 3, 4 and 6 (~relpos~). The coefficient of determination for first response component is 0.8 and second response component is 0.7 (~R2~). The eigenvalues of predictor components decay exponentially by the factor of 0.6 (~gamma~) but the eigenvalues of response components are constant (but can be set to exponential decay) (~eta~). (*c*) Visualization of the true properties of simulated data (regression coefficients, true and estimated covariance between response and predictors components) (*d*) Additional analysis (*e*) Download option of simulated data. 
** Conclusion
- Whether comparing methods or assessing and understanding properties of any methods, tools or procedure; simulated data allows controlled tests for researchers. However, researchers spend enormous amount of time for creating such simulation tools so that they can obtain particular nature of data. We believe that this tool along with R-package and the easy to use shiny web interface will become an assistive tool for researchers in this respect.
* TODO R package:: ~simrel~ [1/7]
DEADLINE: <2017-11-01 on.>
- [ ] Convert ~simulatr~ $\rightarrow$ ~simrel~
- [ ] Univariate simrel (~simrel~) $\rightarrow$ ~unisimrel~ function
- [ ] Include ~mbrd~ function for creating fractional design from old simrel package
- [ ] Update documentation with many examples and cases 
- [ ] Introduce about shiny application and rstudio gadget on the readme file
- [ ] Link to package documentation site
- [X] Move the repository ~therimalaya/simulatr -> simulatr/simrel~

* TODO Shiny application for ~simrel~ [0/2]
DEADLINE: <2017-11-05 sø.>
- [ ] Fix covariance plot (bigger text, aspect ratio etc)
- [ ] Model fitting tab:: Coefficient comparison plot, estimation and prediction error plot

* References

