# Introduction

Technological advancement has opened a door for complex and sophisticated scientific experiments that was not possible before. Due to this change, enormous amounts of raw data are generated which contains massive information but difficult to excavate. Finding information and performing scientific research on these raw data has now become another problem. In order to tackle this situation new methods are being developed. However, before implementing any method, it is essential to test its performance. Often, researchers use simulated data for the purpose which itself is a time-consuming process. The main focus of this paper is to present a simulation method, along with an r-package called `simrel-m`, that is versatile in nature and yet simple to use. 

The simulation method we are discussing here is based on principal of relevant space for prediction [@helland1994comparison]  which assumes that there exists a subspace in the complete space of response variables that is spanned by a subset of eigenvectors of predictor variables. The r-package based on this method lets user to specify various population properties such as  which components of predictors $(\mathbf{X})$ are relevant for a component of responses $\mathbf{Y}$ and how the eigenvalues of $\mathbf{X}$ decreases. This enables the possibility to construct data for evaluating estimation methods and methods developed for variable selection. 

Among several literatures in simulation (<span style="color:red;">\color{red}`which literatures`</span>), @ripley2009stochastic has exhaustively discussed the topic. In addition, many literatures (<span style="color:red;">\color{red}`which literatures`</span>) are available on studies which has implemented simulated data in order to investigate new estimation methods and prediction strategy [see: @cook2015simultaneous; @cook2013envelopes; @helland2012near]. However, most of the simulations in these studies is developed to address their specific problem. A systematic tool for simulating linear model data with single response, which could serve as a general tool for all such comparisons, was presented in @saebo2015simrel and as r-package `simrel`. This paper extends `simrel` in order to simulate linear model data with multivariate response with an r-package `simrel-m`.

The r-package `simrel-m` uses model parameterization which is based on the concept of relevant components @helland1994comparison where it is assumed that a subspace of response $\mathbf{Y}$ is spanned by a subset of eigenvectors corresponding to predictor space. A response space can be thought to have two mutually orthogonal space -- relevant and irrelevant. Here the space of response matrix for which the predictors are relevant is termed as response components, and we assume that each response component is spanned by an exclusive subset of predictor variables. In this way we can construct a set of predictor variables which has non-zero regression coefficients. This also enables user to have uninformative predictors which can be detected during variable selection procedure. In addition, user can control signal-to-noise ratio for each response components with a vector of population coefficient of determination $\boldsymbol{\rho}^2$. Further, the collinearity between predictor variables can also be adjusted by a factor $\gamma$ which controls decay factor of eigenvalue of $\mathbf{X}$ matrix. @helland1994comparison showed that if the direction of large variability (i.e., component corresponding to large eigenvalues) are also relevant relevant predictor space, prediction is relatively easy. In contrast, if the relevant predictors are on the direction of low variability, prediction becomes difficult. Table~\@ref(tab:parameters) shows all the parameters that a user can specify in `simrel-m`.

Table: (#tab:parameters) Parameters for simulation used in this study

| Parameters             | Description                                                                                  |
| :--------------------: | -------------------------------------------------------------------------------------------- |
| $n$                    | number of observations                                                                       |
| $p$                    | number of predictor variables                                                                |
| $q$                    | numbers of relevant predictors for each latent component of response variables               |
| $l$                    | number of informative latent component of response variables (response components)           |
| $m$                    | number of response variables                                                                 |
| $\gamma$               | degree of collinearity (factor that control the decrease of eigenvalue of $\mathbf{X}$)      |
| $\mathcal{P}$          | position index of relevant predictor components for each response components                 |
| $\mathcal{S}$          | position index of response components to combine relevant and irrelevant response variable   |
| $\boldsymbol{\rho}^2$  | population coefficient determination for each response components                            |

Based on random regression model in equation~\@ref(eq:model1), we discuss some of these parameters in details. 

Out of $p$ predictor variables only $q$ of them are relevant and has non-zero regression coefficients $(\beta_{ij} \ne 0)$. If $\boldsymbol{e}_i, \; i = 1, 2, \ldots, p$ be the eigenvectors corresponding to $\mathbf{X}$, then, for some vector of $\boldsymbol{\eta}_i, i = 1, \ldots, p$, 

\begin{equation}
\mathbf{B} = \left(\beta_{ij}\right) = 
  \begin{bmatrix} 
    \boldsymbol{\eta}_{11} & \ldots & \boldsymbol{\eta}_{1p} \\
    \vdots & \ddots & \vdots \\
    \boldsymbol{\eta}_{m1} & \ldots & \boldsymbol{\eta}_{mp}
  \end{bmatrix} 
  \begin{bmatrix} 
    \mathbf{e}_{11} & \vdots & \mathbf{e}_{1p} \\
    \vdots & \ddots & \vdots \\
    \mathbf{e}_{p1} & \vdots & \mathbf{e}_{pp}
  \end{bmatrix} = \mathcal{G}\mathbf{E}
(\#eq:beta-eigenvector-relation)
\end{equation}

The number of terms in equation~\@ref(eq:beta-eigenvector-relation) could reduce because of two reasons,

a) Some elements in $\mathcal{G}$ are zero, i.e. some $\eta_{ij}$ are zero for response $j$
b) There are coinciding eigenvalues of $\Sigma_{xx}$ such that it is enough to have one eigenvector in equation~\@ref(eq:beta-eigenvector-relation).

Let there are $k$ number predictor components that are relevant for any of the response. The $\mathcal{P}$ contains the indices of these position for each response components.

Thus we can say that the first row of $\mathbf{B}$ contains $k_1$ non-zero values corresponding to first response components. The second row contains $k_2$ non-zero values corresponding to second response components and so on such that $\sum_j{k_j} = k$, the total number of components of $\mathbf{X}$ that are relevant for any of the response.

---
Let us consider a random regression model in equation~\@ref(eq:model1) as our point of departure.

\begin{equation}
  \mathbf{Y} = \boldsymbol{\mu}_Y + \mathbf{B}^t (\mathbf{X} - \boldsymbol{\mu}_X) + \boldsymbol{\epsilon}
  (\#eq:model1)
\end{equation}
where $\mathbf{Y}$ is a response matrix with $m$ response variables $y_1, y_2, \ldots y_m$ with mean vector of $\boldsymbol{\mu}_Y$; $\mathbf{X}$ is vector of $p$ predictor variables and the random error term $\boldsymbol{\epsilon}$ is assumed to follow $N(\boldsymbol{0},\; \boldsymbol{\Sigma}_{Y|X})$. In addition, we assume equation~\@ref(eq:model1) as a random regression model where $\mathbf{X} \sim N\left(\boldsymbol{\mu}_X, \boldsymbol{\Sigma}_{XX}\right)$ independent of $\boldsymbol{\epsilon}$.

## Model Specification

A multi-response multivariate general linear model in equation-\@ref(eq:model1) is conidered as a simulation model.

Being an extension of `simrel` package, a quick summary of the procedure used in that package  helps to underestand the literature in this paper.

### An overview of `simrel`

`Simrel` is based on uni-response linear model as in equation~\@ref(eq:simrel-model).

\begin{equation}
(\#eq:simrel-model)
  \begin{bmatrix}
    y \\ \mathbf{X}
  \end{bmatrix} \sim
  \mathcal{N}\left(
    \begin{bmatrix}
      \mu_y \\ \boldsymbol{\mu_X}
    \end{bmatrix},
    \begin{bmatrix}
      \sigma_y^2               & \boldsymbol{\sigma_{Xy}}^t \\
      \boldsymbol{\sigma_{Xy}} & \boldsymbol{\Sigma_{XX}}
    \end{bmatrix}
  \right)
\end{equation}

 Equivalently,

\begin{equation}
  \begin{bmatrix}\mathbf{Y}\\ \mathbf{X}\end{bmatrix} \sim N(\boldsymbol{\mu}, \boldsymbol{\Sigma})
  = N \left(
    \begin{bmatrix}
      \boldsymbol{\mu}_Y \\
      \boldsymbol{\mu}_X
    \end{bmatrix},
    \begin{bmatrix}
      \boldsymbol{\Sigma}_{YY} & \boldsymbol{\Sigma}_{XY}^t \\
      \boldsymbol{\Sigma}_{XY} & \boldsymbol{\Sigma}_{XX}
    \end{bmatrix}
  \right)
  (\#eq:model2)
\end{equation}

Here,

$\boldsymbol{\Sigma}_{YY}$ :                    Covariance Matrix of response $\mathbf{Y}$ without given $\mathbf{X}$            
$\boldsymbol{\Sigma}_{XY}$ :                    Covariance Matrix between $\mathbf{X}$ and $\mathbf{Y}$                      
$\boldsymbol{\Sigma}_{XX}$ :                    Covariance matrix of predictor variables $\mathbf{X}$                            
$\boldsymbol{\mu}_X$ and $\boldsymbol{\mu}_Y$ : Mean vectors of response $\mathbf{Y}$ and predictor $\mathbf{X}$ respective 

According to the theory of Multivariate Normal Distribution, we can express different parameters interms of $\mathbf{X}$, $\mathbf{Y}$ and the covariance structure.

### Model Parameterization



_Parameter Definition:_

Before continuing any further, it is necessary to define the parameters used here,


In the following section, some of these parameters are discussed in detail. The discussion has considered random $\mathbf{X}$ regression model with $m$ response as given in equation~\@ref(eq:model1).

_Parameters Explanation and Notation Used:_

Let $m$ responses are spanned completely by $l$ response components. These $l$ response components are combined with $m-l$ standard normal vectors by user defined criteria to get $m$ responses after successive orthogonal transformation. Out of $q$, let $q_j,\; j = 1, \ldots l$ be the number of predictors that is relevant for response $j$. Let $c_j$ be the number of eigenvectors/ components that completely span $j^\text{th}$ predictor space containing $q_j$ number of predictors. Further, the position of these components for $j^\text{th}$ response be in index set $\mathcal{P}_j$. Here it is also assumed that the eigenvalues corresponding to $\mathbf{X}$ declines successively such that $\lambda_i, i = 1, \ldots, p$ such that $\lambda_i \ge \lambda_k, i > k$ are the eigen values of $\mathbf{X}$. The position index of eigenvalues corresponding to response $j$ is in the set $\mathcal{P}_j$. We assume that the index are ordered within each sets so that, $j^\text{th}$ index set contains $c_j$ number of components. The eigenvalues corresponding to these components in $\mathcal{P}_j$ set is $\lambda_{\mathcal{P}_{jk}}, k = 1, \ldots c_j$ such that $\lambda_{\mathcal{P}_{jk}} > \lambda_{\mathcal{P}_{jk'}}$ for $k > k'$. In `Simrel-M` package, we refer this position by `relpos` argument. In addition, we suppose that the relevant components are exclusive for each response.

_An Example:_

Suppose we have a situation like,

-------------------------------------------------------------- ------------------- --- ---------------------------
                                            Number of response $(m)$                =   5                         
                                 Number of response components $(l)$                =   3                         
                 Position of relevant component for response 1 $(\mathcal{P}_1)$    =   $\left\{ 1, 3 \right\}$   
                 Position of relevant component for response 2 $(\mathcal{P}_2)$    =   $\left\{ 2, 4, 5 \right\}$
                 Position of relevant component for response 3 $(\mathcal{P}_3)$    =   $\left\{ 6 \right\}$      
-------------------------------------------------------------- ------------------- --- ---------------------------

such that, $\lambda_1 > \lambda_3$ in $\mathcal{P}_1$ and $\lambda_2 > \lambda_4 > \lambda_5$ in set $\mathcal{P}_2$. Here, the component (eigenvector) 1 and 3 are relevant for response component 1, component 2, 4 and 5 are relevant for response component 2 and component 6 is relevant for response component 3.

In `Simrel-M`, we have assumed that the eigenvalues are decreasing exponentially by factor $\gamma$ and the largest eigenvalue is 1, i.e. for $\gamma > 0$, $\lambda_i = \text{e}^{-\gamma(i-1)}$ for $i = 1, 2, \ldots p$.
