# Introduction Part

The r-package `simrel-m` uses model parameterization which is based on the concept of relevant components @helland1994comparison where it is assumed that a subspace of response $\mathbf{Y}$ is spanned by a subset of eigenvectors corresponding to predictor space. A response space can be thought to have two mutually orthogonal space -- relevant and irrelevant. Here the space of response matrix for which the predictors are relevant is termed as response components, and we assume that each response component is spanned by an exclusive subset of predictor variables. In this way we can construct a set of predictor variables which has non-zero regression coefficients. This also enables user to have uninformative predictors which can be detected during variable selection procedure. In addition, user can control signal-to-noise ratio for each response components with a vector of population coefficient of determination $\boldsymbol{\rho}^2$. Further, the collinearity between predictor variables can also be adjusted by a factor $\gamma$ which controls decay factor of eigenvalue of $\mathbf{X}$ matrix. @helland1994comparison showed that if the direction of large variability (i.e., component corresponding to large eigenvalues) are also relevant relevant predictor space, prediction is relatively easy. In contrast, if the relevant predictors are on the direction of low variability, prediction becomes difficult. Table~\@ref(tab:parameters) shows all the parameters that a user can specify in `simrel-m`.

Table: (#tab:parameters) Parameters for simulation used in this study

| Parameters             | Description                                                                                  |
| :--------------------: | -------------------------------------------------------------------------------------------- |
| $n$                    | number of observations                                                                       |
| $p$                    | number of predictor variables                                                                |
| $q$                    | numbers of relevant predictors for each latent component of response variables               |
| $l$                    | number of informative latent component of response variables (response components)           |
| $m$                    | number of response variables                                                                 |
| $\gamma$               | degree of collinearity (factor that control the decrease of eigenvalue of $\mathbf{X}$)      |
| $\mathcal{P}$          | position index of relevant predictor components for each response components                 |
| $\mathcal{S}$          | position index of response components to combine relevant and irrelevant response variable   |
| $\boldsymbol{\rho}^2$  | population coefficient determination for each response components                            |

Based on random regression model in equation~\@ref(eq:model1), we discuss some of these parameters in details.

Out of $p$ predictor variables only $q$ of them are relevant and has non-zero regression coefficients. If $\boldsymbol{e}_i, \; i = 1, 2, \ldots, p$ be the eigenvectors corresponding to $\mathbf{X}$, then, for some vector of $\boldsymbol{\eta}_j, j = 1, \ldots, m$ for $m$ response variables,

\begin{align}
\mathbf{B} = \left(\beta_{ij}\right) &=
  \begin{bmatrix}
    \boldsymbol{\eta}_{11} & \ldots & \boldsymbol{\eta}_{1p} \\
    \vdots                 & \ddots & \vdots \\
    \boldsymbol{\eta}_{m1} & \ldots & \boldsymbol{\eta}_{mp}
  \end{bmatrix}
  \begin{bmatrix}
    \mathbf{e}_{11} & \vdots & \mathbf{e}_{1p} \\
    \vdots          & \ddots & \vdots \\
    \mathbf{e}_{p1} & \vdots & \mathbf{e}_{pp}
  \end{bmatrix} \\ &=
  \begin{bmatrix}\boldsymbol{\eta}_{1} \\ \vdots \\ \boldsymbol{\eta}_{m}\end{bmatrix}_{m \times p}
  \begin{bmatrix}\mathbf{e}_{1} & \ldots & \mathbf{e}_{p}\end{bmatrix}_{p \times p}
(\#eq:beta-eigenvector-relation)
\end{align}

The number of terms in equation~\@ref(eq:beta-eigenvector-relation) may be reduced by two mechanisms:

a) Some elements in $\boldsymbol{\eta}_j, j = 1, \ldots m$ are zero
b) There are coinciding eigenvalues of $\boldsymbol{\Sigma}_{xx}$ such that it is enough to have one eigenvector in equation~\@ref(eq:beta-eigenvector-relation).

Let there are $k$ number predictor components that are relevant for any of the response. The $\mathcal{P}$ contains the indices of these position for each response components. Here the order of components of predictor is defined by a decreasing set of eigenvalues such that $\lambda_1 \ge \ldots \ge \lambda_p > 0$. In `simrel-m` package, these set of position is referred as `relpos`. For example, if $\mathcal{P} = {{1, 2}, {3, 5}, {4}}$ then we  can say that there are 3 informative space in response such that components 1 and 2 of predictor variable is relevant for first response component; component 3 and 5 of predictor are relevant for second response component and fourth predictor component is relevant for third response component. In addition, $\lambda_1 \ge \ldots \ge \lambda_5$ are relevant for some response.

In `simrel-m`, these 3 response components are combined with non-informative vectors for desired number of response variables. This is referred as $\mathcal{S}$ and `ypos` in `simrel-m` package. If $\mathcal{S} = {{1, 4}, {2}, {3, 5}}$ then we can say that there are 5 response variables which has 3 dimensional informative space. Since response components 1, 2 and 3 are informative, from the indices of $\mathcal{S}$, first response component is combined with non-informative fourth component and third informative component is combined with fifth non-informative component. In this way, we will obtain a set of 5 response variables for which predictor component 1 and 2 will be relevant for response 1 and 4; predictor component 3 and 5 will be relevant for response 2 and predictor component 4 will be relevant for response 3 and 5.

For simplification, an assumption is made that all $p$ eigenvalues of $\boldsymbol{\Sigma}_{XX}$ decrease exponentially as $e^{-\gamma (i - 1)}$ for $i = 1, \ldots p$ and some positive constant $\gamma$. This way, the $p$ eigenvalues depends on single variables $\gamma$ such that when $\gamma$ is large, eigenvalues decreases sharply referring high degree of multi-collinearity in predictor variables.

Here we have assumed that the relevant components are know, as in @helland1994comparison, which is rare in practice. But in comparative studies of prediction methods, this can help to explain interesting cases. For example, simultaneous envelope [@cook2015simultaneous] has discussed about the informative (material) and uninformative (immaterial) space on both $\mathbf{X}$ and $\mathbf{Y}$. In this case, `simrel-m` can provide a simulated data with various interesting cases for its assessment and comparison with other methods.

# Statistical Model Part

Simulation of $(\mathbf{Y, X})$ for model~\@ref(eq:rand-reg-model) requires the fact that -- a set of latent variable spanning $\mathbf{X}$ and $\mathbf{Y}$ will contain same information in different structure. With two matrices $\mathbf{R}_{p\times p}$ and $\mathbf{Q}_{q \times q}$ with rank $p$ and $q$ respectively, lets define a transformation as $\mathbf{Z} = \mathbf{RX}$ and $\mathbf{W} = \mathbf{QY}$ so that,

# Simulation strategy Follows
Thus, on the basis of these mathematical backgrounds, the simulation strategy follows,
a) Construct covariance structure of $\mathbf{W}$ and $\mathbf{Z}$ satisfying given parameters
b) Simulate $\mathbf{W}$ and $\mathbf{Z}$ from random standard normal distribution
c) Rotation $\mathbf{Z}$ by orthonormal matrix $\mathbf{R}$ to yield $\mathbf{X} = \mathbf{R}^t \mathbf{Z}$
d) Rotation of $\mathbf{W}$ by orthogonal matrix $\mathbf{Q}$ to yield $\mathbf{Y} = \mathbf{Q}^t \mathbf{W}$
e) For simplification, we assume that no common components of $\mathbf{X}$, i.e. $\mathbf{Z}$, relevant for $\mathbf{W}$. For example, if component 1 and component 2 are relevant for $\mathbf{W}_1$, they are not relevant for other $\mathbf{W}$'s.

# Model parameterization {#model-parameter} #

Eigenvalue decomposition principal states that a variance-covariance matrix $\boldsymbol{\Sigma}$ can be decomposed as,

\begin{equation}
  \Sigma = \mathbf{E}\Lambda \mathbf{E}^t
\end{equation}

where, $\mathbf{E} = (\mathbf{e}_1, \mathbf{e}_2, \ldots \mathbf{e}_p)$ is an orthogonal matrix of eigenvectors and $\Lambda$ is a diagonal matrix of eigenvalues $\lambda_1 \le \lambda_2 \le \ldots \lambda_p$. From expression in equation~\@ref(eq:cov-yx-wz), $\boldsymbol{\Sigma}_{XX}$ and $\boldsymbol{\Sigma}_{WW}$ can have similar decomposition with some suitable choice of orthonormal matrix $\mathbf{R}$ and $\mathbf{Q}$ respectively.

In this study, all the components of $\mathbf{Y}$, i.e. $\mathbf{W}$ are considered to be uncorrelated. Since, the component structure also contains the irrelevant components, each of their correlation with others are considered to be zero. Hence, the unconditional covariance structure for the component matrix ($\mathbf{W}$) is $\mathbf{I}_m$. Furthermore, if $\boldsymbol{\Sigma}_{ZZ} = \Lambda = \text{diag}({\lambda_1, \lambda_2, \ldots, \lambda_p})$, where $\lambda_i, i = 1, \ldots p$ are eigenvalues of $\mathbf{X}$, the expression in \mbox{equation~\@ref(eq:cov-yx-wz)} helps to simulate $\mathbf{X}$ from $\mathbf{R}$, the orthonormal rotation matrix and its eigen structure $\boldsymbol{\Sigma}_{ZZ}$. Similarly from $\Sigma_{WW} = \mathbf{I}_m$ and rotaion matrix $\mathbf{Q}$, we can simulate $\mathbf{Y}$.

Let $\mathbf{W}_1, \ldots, \mathbf{W}_l$ are the components of $Y$ that are relevant to $\mathbf{Z}$ and consequently $\mathbf{X}$, $\mathbf{W}_{l+1}, \ldots, \mathbf{W}_q$ are not the outcome of $\mathbf{Z}$, the principal components of $\mathbf{Z}$ that are relevant for $\mathbf{W}$ are applicable for $\mathbf{W}_1, \ldots, \mathbf{W}_l$ only. The covariance matrix of $\mathbf{W}$ and $\mathbf{Z}$ ($\boldsymbol{\Sigma}_{WZ}$) is constructed referring to the terminology in @helland1994comparison that the principal components are termed as relevant for which $\boldsymbol{\Sigma}_{WZ}$ are non-zero.

Assume $a_1, \ldots, a_l$ number of principal components of $\mathbf{X}$ are relevant to $\mathbf{W}_1, \ldots, \mathbf{W}_l$ respectively. Let $\mathcal{P}_1, \ldots, \mathcal{P}_l$ are the sets of positions of these components, then $(\Sigma_{WZ})_{ij} \ne 0$ if $j \in \mathcal{P}_i$, $i = 1, \ldots, l$ and zero otherwise. This follows us to the matrix of regression coefficients as,

\begin{equation}
  \mathbf{A} =
  \begin{cases}
    \boldsymbol{\Sigma}_{WZ}\boldsymbol{\Sigma}_{ZZ}^{-1} =
    \sum_{j \in \mathcal{P}_i}{\left(\frac{\sigma_{ij}}{\lambda_j} \mathbf{t}_j\right)} & \text{ for } i = 1, \ldots, l \\
    0 & \text{ otherwise }
  \end{cases}
\end{equation}

where, $\mathbf{t}_j$ is a $p$-vector with 1 at position $j$ and zero otherwise. As in the previous version of simrel by @saebo2015simrel, eigenvalues of $\boldsymbol{\Sigma}_{XX}$ is assumed to be different and has adopted the parametric representation as $\lambda_j 	=	e^{-\nu(j - 1)}\text{ for } \nu>0 \text{ and } j = 1, \ldots p$. Here, the parameter $\nu$ regulates the decline of $\lambda_j, j = 1, \ldots p$. Without loss of generality, for further simplification, the first and largest eigenvalues are set to one.

For complete parametrization of the matrix $\boldsymbol{\Xi}_{WZ}$ in equation~\@ref(eq:model3), covariances between $W$ and $Z$ ($\boldsymbol{\Sigma}_{WZ}$)  should be constructed such that it is positive definite and satisfy the relation,

\begin{align}
  \boldsymbol{\mathcal{R}}^{2}_{WZ}                                      &=
    \boldsymbol{\Sigma}_{WZ}\boldsymbol{\Sigma}^{-1}_{ZZ}\boldsymbol{\Sigma}_{ZW}\boldsymbol{\Sigma}_{WW}^{-1} \nonumber \\
  \text{i.e, } \boldsymbol{\mathcal{R}}_{WZ}^{2}\boldsymbol{\Sigma}_{WW} &=
    \boldsymbol{\Sigma}_{WZ}\boldsymbol{\Lambda}^{-1}\boldsymbol{\Sigma}_{ZW}
(\#eq:sigmaRhoRelation)
\end{align}

For given $\boldsymbol{\mathcal{R}}_{WZ}^{2}$ and $\Sigma_{WW} = \mathbf{I}_m$, equation~\@ref(eq:sigmaRhoRelation) will be satisfied for some $\boldsymbol{\Sigma}_{WX}$ whose rows correspond to the relevant components for $\mathbf{W}$. As we have considered the situation that no relevant components are common, elements in $\boldsymbol{\Sigma}_{WZ}$ are sampled from a uniform distribution $\mathcal{U}(-1, 1) = \{s_{\mathcal{P}_{1i}}, s_{\mathcal{P}_{2i}}, \ldots s_{\mathcal{P}_{pi}}\}$, for each $i = 1, \ldots q$ as in @saebo2015simrel such that,

$$
\left(\boldsymbol{\sigma}_{WZ}\right)_{ij} = \text{sign}\left(s_{ij}\right)
\sqrt{
  \frac
    {\boldsymbol{\mathcal{R}}_{WZ}^{2}.\left|s_{ij}\right|}
    {\sum_{k\in\mathcal{P}_i}{\left|s_{ik}\right|}}
  \lambda_{j}
}
$$

for $j  \in \mathcal{P}_i$ and for each $i = 1, \ldots q$
